[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.92.0"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[dev]
  framework = "hugo"
  command = "hugo server -D"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = true

# Configuración específica de cabeceiras para CSP
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-src 'self'"